apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Local users
  accounts.sarthak: apiKey,password123

  # Optional: customize login banner
  application.instanceLabelKey: argocd.argoproj.io/instance