apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, sarthak, role:readonly
  policy.default: role:readonly
  # no need for a separate account entry here; credentials are in argocd-cm
  accounts.sarthak: password123