apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, sarthak, role:readonly
  policy.default: role:readonly
  accounts.sarthak: apiKey123   # <-- password/apiKey for Sarthak